[package]
name = "rust-crud-actix"
version = "0.1.0"
edition = "2021"

[dependencies]
async-std = { version = "1.13.0", features = ["attributes"] }
actix-web = "4.9.0"
sqlx = { version = "0.8", features = ["runtime-async-std", "sqlite"] }
